# -*- coding: utf-8 -*-
"""count files.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rqus5ww4YVl3_LEoa_-MCgCjb1j3GIvG
"""

from google.colab import drive
drive.mount('/content/drive')

import os
a=['Orange_October/Healthy','Orange_October/Decayed','Orange_October/Infected','Orange_October/Other Leaves']
for FOLDER_PATH in a:
  ROOT_PATH = '/content/drive/MyDrive/'
  print(FOLDER_PATH,len(os.listdir(os.path.join(ROOT_PATH, FOLDER_PATH))))